# Example static transforms: list of transforms to publish at startup
# Each item may contain:
#  - odom_frame_id / parent: (string) parent frame
#  - base_frame_id / child: (string) child frame
#  - translation: {x: <float>, y: <float>, z: <float>}
#  - rotation_rpy: [roll, pitch, yaw]  (radians) or rotation: {roll:, pitch:, yaw:}

static_tf_broadcaster:
  ros__parameters:
    transforms:
      t0:
        odom_frame_id: "odom"
        base_frame_id: "camera_init"
        translation:
          x: 0.0
          y: 0.0
          z: 0.0
        rotation:
          roll: 0.0
          pitch: 0.0
          yaw: 0.0

      t1:
        odom_frame_id: "aft_mapped"
        base_frame_id: "base"
        translation:
          x: 0.2
          y: 0.0
          z: 0.0
        rotation:
          roll: 0.0
          pitch: 0.0
          yaw: 3.1415926
      t2:
        odom_frame_id: "base"
        base_frame_id: "base_link"
        translation:
          x: 0.0
          y: 0.0
          z: 0.0
        rotation:
          roll: 0.0
          pitch: 0.0
          yaw: 0.0